export { default as Topbar } from "./Topbar/Topbar";
export { default as Intro } from "./Intro/Intro";
export { default as Portfolio } from "./Portfolio/Portfolio";
export { default as Testimonials } from "./Testimonials/Testimonials";
export { default as Contacts } from "./Contacts/Contacts";
export { default as Footer } from "./Footer/Footer";
export { default as Menu } from "./Menu/Menu";
export { default as New } from "./News/New";
export { default as NewsCat } from "./News/NewCat/NewsCat";
